[package]
name = "ch2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.3"
crossbeam-channel = "0.5.5"
parking_lot = "0.12.1"
syn = "1.0.98"
quote = "1.0.20"
proc-macro2 = "1.0.40"